Repository BBD-LevelUps-withBandH/planning-poker, pull requests merged in 2024-06, with the labels that each got.

#14 Rooms and Voting and Democracy
  planning-web/index.html
  planning-web/package.json
  planning-web/src/Agenda/Agenda.css
  planning-web/src/Agenda/Agenda.jsx
  planning-web/src/App.jsx
  planning-web/src/NavBar/NavBar.css
  planning-web/src/Room/Room.css
  planning-web/src/Room/Room.jsx
  planning-web/src/RoomChoose/RoomChoose.css
  planning-web/src/RoomChoose/RoomChoose.jsx
  planning-web/src/UserChoice/UserChoice.css
  planning-web/src/UserChoice/UserChoice.jsx
  planning-web/src/chatgpt/uuid.js
  planning-web/src/index.css
  planning-web/yarn.lock
Labels: enhancement, good first issue

#27 Feature/cognito api
  .gitignore
  planning-web/package.json
  planning-web/src/App.jsx
  planning-web/src/AuthHandler.jsx
  planning-web/src/RoomChoose/RoomChoose.jsx
  planning-web/src/main.jsx
  planning-web/yarn.lock
Labels: enhancement

#30 Web/backend integration
  planning-web/src/Agenda/Agenda.jsx
  planning-web/src/App.jsx
  planning-web/src/AuthHandler.jsx
  planning-web/src/Room/Room.jsx
  planning-web/src/RoomChoose/RoomChoose.jsx
  planning-web/src/UserChoice/UserChoice.jsx
  planning-web/src/backend.js
  planning-web/src/handleSignIn.js
  planning-web/src/main.jsx
  planning-web/yarn.lock
Labels: bug, enhancement

#32 adding origin to cors
  server/index.js
Labels: bug
